
 CREATE TABLE "SENSOR"."PATIENT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"BIRTHDATE" DATE NOT NULL ENABLE, 
	"AGE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PATIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES" ;

  CREATE TABLE "SENSOR"."DOCTOR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DOCTOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES" ;


  CREATE TABLE "SENSOR"."SENSOR" 
   (	"NUMBER_OF_SENSORS" NUMBER NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"NUM" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDPATIENT" NUMBER NOT NULL ENABLE, 
	"SERVICECOD" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"SERVICEDEC" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ADMDATE" DATE NOT NULL ENABLE, 
	"BED" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "SENSOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES"  ENABLE, 
	 CONSTRAINT "SENSOR_FK1" FOREIGN KEY ("IDPATIENT")
	  REFERENCES "SENSOR"."PATIENT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES" ;

  CREATE TABLE "SENSOR"."CARETEAM" 
   (	"IDSENSOR" NUMBER NOT NULL ENABLE, 
	"IDDOCTOR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "CARETEAM_PK" PRIMARY KEY ("IDDOCTOR", "IDSENSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES"  ENABLE, 
	 CONSTRAINT "CARETEAM_FK2" FOREIGN KEY ("IDDOCTOR")
	  REFERENCES "SENSOR"."DOCTOR" ("ID") ENABLE, 
	 CONSTRAINT "CARETEAM_FK1" FOREIGN KEY ("IDSENSOR")
	  REFERENCES "SENSOR"."SENSOR" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES" ;


  CREATE TABLE "SENSOR"."DATA" 
   (	"IDDATA" NUMBER NOT NULL ENABLE, 
	"IDSENSOR" NUMBER NOT NULL ENABLE, 
	"BODYTEMP" NUMBER NOT NULL ENABLE, 
	"BLOODPRESS_SYSTOLIC" NUMBER NOT NULL ENABLE, 
	"BLOODPRESS_DIASTOLIC" NUMBER NOT NULL ENABLE, 
	"BPM" NUMBER NOT NULL ENABLE, 
	"SATO2" NUMBER NOT NULL ENABLE, 
	"TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "DATA_PK" PRIMARY KEY ("IDDATA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES"  ENABLE, 
	 CONSTRAINT "DATA_FK1" FOREIGN KEY ("IDSENSOR")
	  REFERENCES "SENSOR"."SENSOR" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SENSORS_TABLES" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SENSOR"."DATA_TRG" 
BEFORE INSERT ON DATA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDDATA IS NULL THEN
      SELECT DATA_SEQ.NEXTVAL INTO :NEW.IDDATA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SENSOR"."DATA_TRG" ENABLE;