main: main.cpp Our3d.cpp OurXml.cpp tinyxml2.cpp
	g++ main.cpp Our3d.cpp OurXml.cpp tinyxml2.cpp -o main -lGL -lGLU -lglut  


cone:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/1_Fase/cone.xml"

caixa:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/1_Fase/box.xml"

esfera:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/1_Fase/sphere.xml"

plano:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/1_Fase/plane.xml"

