main: main.cpp
	g++ main.cpp  -o main 

plano:
	./main plane 20 "/home/goncalo/Documentos/3ANO/CG/PROJECTO/4_Fase/CG_testes/3d/plane.3d"

esfera:
	./main sphere 10 30 30 "/home/goncalo/Documentos/3ANO/CG/PROJECTO/4_Fase/CG_testes/3d/sphere.3d"

caixa:
	./main box 20 20 20 10 "/home/goncalo/Documentos/3ANO/CG/PROJECTO/4_Fase/CG_testes/3d/box.3d"

cone:
	./main cone 10 20 30 30 "/home/goncalo/Documentos/3ANO/CG/PROJECTO/4_Fase/CG_testes/3d/cone.3d"

bezier:
	./main bezier "/home/goncalo/Documentos/3ANO/CG/PROJECTO/4_Fase/CG_testes/patch/teapot" 20 "/home/goncalo/Documentos/3ANO/CG/PROJECTO/4_Fase/CG_testes/3d/tea.3d"