main: main.cpp Our3d.cpp OurXml.cpp tinyxml2.cpp
	g++ main.cpp Our3d.cpp OurXml.cpp tinyxml2.cpp -o main -lGL -lGLU -lglut  


cone:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/2_Fase/CG_testes/xml/cone.xml"

caixa:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/2_Fase/CG_testes/xml/caixa.xml"

esfera:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/2_Fase/CG_testes/xml/esfera.xml"

plano:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/2_Fase/CG_testes/xml/plano.xml"

solar:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/2_Fase/CG_testes/xml/SistemaSolar.xml"
