insert into POSICAO values (1,'Guarda Redes');
insert into POSICAO values (2,'Defesa Direito');
insert into POSICAO values (3,'Líbero');
insert into POSICAO values (4,'Defesa Central');
insert into POSICAO values (5,'Defesa Esquerdo');
insert into POSICAO values (6,'Trinco');
insert into POSICAO values (7,'Extremo Direito');
insert into POSICAO values (8,'Médio');
insert into POSICAO values (9,'Ponta de Lança');
insert into POSICAO values (10,'Médio Ataque');
insert into POSICAO values (11,'Extremo Esquerdo');
insert into POSICAO values (12,'Ala');
