main: main.cpp Our3d.cpp OurXml.cpp tinyxml2.cpp
	g++ main.cpp Our3d.cpp OurXml.cpp tinyxml2.cpp CatmullRom.cpp -o main -lGL -lGLU -lglut -lGLEW  


cone:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/cone.xml"

caixa:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/caixa.xml"

esfera:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/esfera.xml"

plano:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/plano.xml"

movement:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/teamovement.xml"

tea: 
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/tea.xml"

solar:
	./main "/home/goncalo/Documentos/3ANO/CG/PROJECTO/3_Fase/CG_testes/xml/SistemaSolar.xml"
